import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import dynamic from "next/dynamic";
const Dashboard = dynamic(() => import("shop/dashboard"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Main App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav />
        {/* <div className={styles.description}> */}
        <p>Welcome to Main app</p>
        <Dashboard />
        {/* </div> */}
        <Footer />
      </main>
    </>
  );
}
