import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import Head from "next/head";

const Nav = dynamic(() => import("main/nav"));
const Footer = dynamic(() => import("main/footer"));
export default function Catalog() {
  return (
    <>
      <Head>
        <title>Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav />
        <h1>Catalog page II</h1>
        <Footer />
      </main>
    </>
  );
}
